# Generated by Django 3.0.5 on 2021-05-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_availablity_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableBeds',
        ),
    ]
