# Generated by Django 3.0.5 on 2021-05-26 05:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bed_availablity_service', '0002_delete_availablebeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBeds',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('updated_at', models.CharField(max_length=14)),
                ('hospitals', djongo.models.fields.JSONField(default=dict)),
                ('safe_homes', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
    ]
