# Generated by Django 3.0.5 on 2021-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_availablity_service', '0003_availablebeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebeds',
            name='date',
            field=models.CharField(default='01012021', max_length=10),
        ),
        migrations.AlterField(
            model_name='availablebeds',
            name='updated_at',
            field=models.CharField(default='01012021000000', max_length=16),
        ),
    ]
